import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, ArrowsOut, ArrowsClockwise, Cube, SquaresFour, FolderSimple, FileText, UploadSimple, CaretRight, CaretLeft, CaretDown, X, LinkSimple, CheckCircle, Circle, LockSimple, SpinnerGap, Crosshair, MagnifyingGlass, Keyboard, List, ArrowLeft, Plus, Minus, Planet, Info } from '@phosphor-icons/react';
import Space from './Space.jsx';
import { sampleProject, statusLabel, lanes, laneFor } from './demo.mjs';
import { parsePlan } from './plan-parser.mjs';

const normalizePlan = p => ({...p, tasks:p.tasks.map(t=>({...t, id:t.sourceId||t.id}))});
const StatusIcon=({status,...props})=>{const Icon={complete:CheckCircle,active:SpinnerGap,blocked:LockSimple,pending:Circle}[status]||Circle;return <Icon {...props}/>;};
export default function App(){
  const [projects,setProjects]=useState([sampleProject]), [projectId,setProjectId]=useState('sample'), [planId,setPlanId]=useState('sample-plan');
  const [selected,setSelected]=useState('T2.2'), [epic,setEpic]=useState('all'), [filter,setFilter]=useState('all');
  const [view,setView]=useState('space'), [showLinks,setShowLinks]=useState(true), [resetKey,setResetKey]=useState(0), [focusKey,setFocusKey]=useState(0);
  const [loading,setLoading]=useState(true), [notice,setNotice]=useState(''), [workspaceOpen,setWorkspaceOpen]=useState(false), [workspaceExpanded,setWorkspaceExpanded]=useState(false), [inspectorExpanded,setInspectorExpanded]=useState(false), [taskList,setTaskList]=useState(false), [help,setHelp]=useState(false), [query,setQuery]=useState(''), [importing,setImporting]=useState(false), [importText,setImportText]=useState('');
  const upload=useRef(null);const importCount=useRef(0);
  const project=projects.find(p=>p.id===projectId)||sampleProject;
  const plan=project.plans.find(p=>p.id===planId)||project.plans[0];
  const tasks=plan?.tasks||[];
  const filteredTasks=useMemo(()=>tasks.filter(t=>epic==='all'||t.epicId===epic),[tasks,epic]);
  const visibleTasks=useMemo(()=>lanes.flatMap(l=>{const group=filteredTasks.filter(t=>laneFor(t)===l.id);const first=group.slice(0,4);const chosen=group.find(t=>t.id===selected);if(chosen&&!first.includes(chosen))first[first.length-1]=chosen;return first;}),[filteredTasks,selected]);
  const task=tasks.find(t=>t.id===selected);
  const complete=tasks.filter(t=>t.status==='complete').length, blocked=tasks.filter(t=>t.status==='blocked').length;
  const progress=tasks.length?Math.round(complete/tasks.length*100):0;
  const selectProject=(p)=>{setProjectId(p.id);setPlanId((p.plans.find(plan=>plan.tasks.length)||p.plans[0])?.id);setEpic('all');setSelected(null);setInspectorExpanded(false);setFilter('all');setResetKey(k=>k+1);setWorkspaceOpen(false);};
  const loadPlans=async()=>{
    setLoading(true);
    try {const response=await fetch('/api/plans');if(!response.ok)throw new Error('Could not read local plans');const data=await response.json();
      if(!Array.isArray(data.projects))throw new Error('Local plan reader is unavailable');
      setProjects(current=>[sampleProject,...data.projects.map(p=>({...p,plans:p.plans.map(normalizePlan)})),...current.filter(p=>p.imported)]);
      if(data.warnings?.length)setNotice(data.warnings[0]);
    }catch{setNotice('Local plans are unavailable. You can still import a Markdown plan.');}finally{setLoading(false);}
  };
  useEffect(()=>{loadPlans();},[]);
  useEffect(()=>{const listener=e=>{if((help||taskList||importing)&&e.key==='Tab'){const items=[...document.querySelectorAll('.modal button:not(:disabled),.modal input,.modal select,.modal textarea')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}if(e.key==='Escape'){setHelp(false);setTaskList(false);setImporting(false);setWorkspaceOpen(false);setInspectorExpanded(false);}if(e.target instanceof HTMLElement&&['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key.toLowerCase()==='r')setResetKey(k=>k+1);if(e.key==='?')setHelp(h=>!h);};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[help,taskList,importing]);
  useEffect(()=>{
    if(!workspaceOpen)return;
    const drawer=document.querySelector('.sidebar');
    const previous=document.activeElement;
    const focusable=()=>[...drawer.querySelectorAll('a[href],button:not(:disabled),input')].filter(el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden'&&getComputedStyle(el).display!=='none');
    focusable()[0]?.focus();
    const trap=e=>{if(e.key!=='Tab')return;const items=focusable(),first=items[0],last=items.at(-1);if(!drawer.contains(document.activeElement)){e.preventDefault();first?.focus();}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};
    window.addEventListener('keydown',trap);
    return()=>{window.removeEventListener('keydown',trap);const modalControl=document.querySelector('.modal button');if(modalControl)modalControl.focus();else if(previous?.isConnected)previous.focus();};
  },[workspaceOpen]);
  const addImported=(markdown,name)=>{
    const parsed=parsePlan(markdown,{path:name,project:'Imported'});
    const imported=normalizePlan(parsed);
    const byId=new Map(imported.tasks.map(t=>[t.id,t]));
    imported.tasks=imported.tasks.map(t=>({...t,status:t.status==='pending'&&t.dependencies.some(id=>byId.has(id)&&byId.get(id).status!=='complete')?'blocked':t.status}));
    if(!imported.tasks.length){setNotice(`${name} has no recognized task checkboxes. Use stable task IDs such as T1.1.`);return;}
    const id=`import-${++importCount.current}`;
    const p={id,name:name.replace(/\.md$/i,''),imported:true,plans:[{...imported,id:`${id}-plan`}]};
    setProjects(current=>[...current,p]);selectProject(p);setImporting(false);setImportText('');setNotice(`Imported ${imported.tasks.length} tasks from ${name}.`);
  };
  const importFiles=async(event)=>{
    for(const file of [...event.target.files]){
      if(file.size>2_000_000){setNotice(`${file.name} is too large. Import a plan under 2 MB.`);continue;}
      try{addImported(await file.text(),file.name);}catch{setNotice(`Could not parse ${file.name}. Choose a UTF-8 Markdown plan.`);}
    }event.target.value='';
  };
  const selectTask=id=>{const t=tasks.find(t=>t.id===id);if(t&&epic!=='all'&&t.epicId!==epic)setEpic(t.epicId||'all');setSelected(id);setInspectorExpanded(true);setTaskList(false);};
  const collapseInspector=()=>{setInspectorExpanded(false);requestAnimationFrame(()=>{[...document.querySelectorAll('.inspector-toggle-inline,.inspector-toggle-rail button')].find(el=>el.getClientRects().length)?.focus();});};
  const localProjects=projects.filter(p=>!p.sample);
  const matches=localProjects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="app-shell">
    <aside role={workspaceOpen?'dialog':undefined} aria-modal={workspaceOpen||undefined} aria-label="Workspace" className={`sidebar ${workspaceExpanded?'expanded':'compact'} ${workspaceOpen?'open':''}`}>
      <a className="brand" href="#" aria-label="Wazi plan observatory" title="Wazi plan observatory" onClick={e=>e.preventDefault()}><Planet size={30} weight="duotone"/><span>wazi<span className="brand-dot">.</span></span><small>PLAN OBSERVATORY</small></a>
      <div className="workspace-heading"><span>YOUR WORKSPACE</span><div className="workspace-heading-actions"><button className="icon-btn sidebar-expand-toggle" aria-label={workspaceExpanded?'Collapse project sidebar':'Expand project sidebar'} title={workspaceExpanded?'Collapse project sidebar':'Expand project sidebar'} aria-expanded={workspaceExpanded} aria-controls="project-navigation" onClick={()=>setWorkspaceExpanded(value=>!value)}>{workspaceExpanded?<CaretLeft size={16}/>:<CaretRight size={16}/>}</button><button className="icon-btn" aria-label="Refresh local projects" title="Refresh local projects" onClick={loadPlans}><ArrowsClockwise size={15} className={loading?'spin':''}/></button></div></div>
      <button className={`project-row sample ${project.sample?'is-active':''}`} title="Wazi observatory · Example plan" aria-label="Wazi observatory, example plan" aria-current={project.sample?'page':undefined} onClick={()=>selectProject(sampleProject)}><Cube size={19} weight="duotone"/><span><strong>Wazi observatory</strong><small>Example plan</small></span><CaretRight size={13}/></button>
      <div className="local-heading"><span>LOCAL PROJECTS</span><span>{loading?'…':localProjects.length}</span></div>
      <div className="project-search"><MagnifyingGlass size={14}/><input aria-label="Filter projects" placeholder="Find a project" value={query} onChange={e=>setQuery(e.target.value)}/></div>
      <nav className="project-list" id="project-navigation" aria-label="Project plans">{loading?<p className="muted-copy">Reading local plans…</p>:matches.length?matches.map(p=><button key={p.id} title={`${p.name} · ${p.plans.length} ${p.plans.length===1?'plan':'plans'}`} aria-label={`${p.name}, ${p.plans.length} ${p.plans.length===1?'plan':'plans'}, ${p.plans.reduce((n,p)=>n+p.tasks.length,0)} tasks`} aria-current={p.id===project.id?'page':undefined} className={`project-row ${p.id===project.id?'is-active':''}`} onClick={()=>selectProject(p)}><FolderSimple size={17}/><span><strong>{p.name}</strong><small>{p.plans.length} {p.plans.length===1?'plan':'plans'} · {p.plans.reduce((n,p)=>n+p.tasks.length,0)} tasks</small></span></button>):<p className="muted-copy">{query?'No matching projects.':'No local plans found. Import one to begin.'}</p>}</nav>
      <div className="sidebar-bottom"><button className="import-button" title="Import a plan" aria-label="Import a plan" onClick={()=>{setWorkspaceOpen(false);setImporting(true);}}><UploadSimple size={17}/><span>Import a plan</span><Plus size={13}/></button><div className="local-note"><span className="live-dot"/>Local & read only</div><button className="help-button" title="Navigation guide" aria-label="Open navigation guide" onClick={()=>{setWorkspaceOpen(false);setHelp(true);}}><Keyboard size={16}/><span className="help-label">Navigation guide</span><span>?</span></button></div>
    </aside>
    {workspaceOpen&&<button className="mobile-scrim" tabIndex={-1} aria-label="Close workspace" onClick={()=>setWorkspaceOpen(false)}/>}
    <main className={`main ${task?'has-inspector':''}`} inert={workspaceOpen}>
      <header className="topbar"><button className="icon-btn mobile-menu" aria-label="Open workspace" onClick={()=>setWorkspaceOpen(true)}><List size={22}/></button><div className="breadcrumb"><FolderSimple size={15}/><span>{project.name}</span><CaretRight size={12}/><strong>{plan?.title}</strong></div><div className="topbar-actions"><span className={`source-badge ${project.sample?'example':''}`}><span className="live-dot"/>{project.sample?'EXAMPLE PLAN':project.imported?'IMPORTED PLAN':'LOCAL PLAN'}</span><button className="icon-btn inspector-toggle-inline" aria-label={inspectorExpanded?'Collapse task inspector':'Expand task inspector'} title={inspectorExpanded?'Collapse task inspector':'Expand task inspector'} aria-expanded={Boolean(task&&inspectorExpanded)} aria-controls="task-inspector" disabled={!task} onClick={()=>setInspectorExpanded(value=>!value)}><CaretLeft size={17}/></button><button className="icon-btn" aria-label="Show navigation guide" onClick={()=>{setWorkspaceOpen(false);setHelp(true);}}><Info size={18}/></button></div></header>
      <section className="overview"><div><div className="eyebrow"><span>WORK IN PERSPECTIVE</span><span className="tiny-line"/></div><h1>The bigger picture<span>.</span></h1><p>Every step connected. Your next move, clear.</p></div><div className="plan-stats"><div><strong>{tasks.length}</strong><span>total tasks</span></div><div><strong>{complete}<small> / {tasks.length}</small></strong><span>complete</span></div><div><strong className="blocked-count">{blocked.toString().padStart(2,'0')}</strong><span>blocked</span></div></div></section>
      <section className="canvas-toolbar"><div className="view-switch" role="group" aria-label="Plan view"><button className={view==='space'?'active':''} onClick={()=>setView('space')}><Cube size={16}/>3D space</button><button className={view==='map'?'active':''} onClick={()=>setView('map')}><SquaresFour size={16}/>Map</button></div><div className="toolbar-fields">{project.plans.length>1&&<select aria-label="Select plan" value={plan.id} onChange={e=>{setPlanId(e.target.value);setEpic('all');setSelected(null);setInspectorExpanded(false);setResetKey(k=>k+1);}}>{project.plans.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select>}<select aria-label="Select epic" value={epic} onChange={e=>{setEpic(e.target.value);setSelected(null);setInspectorExpanded(false);setResetKey(k=>k+1);}}><option value="all">All epics</option>{(plan.epics||[]).map(e=><option key={e.id} value={e.id}>{e.id} · {e.title}</option>)}</select><button className={`toggle-links ${showLinks?'on':''}`} onClick={()=>setShowLinks(v=>!v)} aria-pressed={showLinks}><LinkSimple size={16}/><span>Dependencies</span><span className="toggle-track"><i/></span></button><button className="icon-btn" aria-label="Open task list" onClick={()=>setTaskList(true)}><List size={18}/></button></div></section>
      <div className="scene-area"><Space tasks={visibleTasks} selected={selected} onSelect={selectTask} showLinks={showLinks} resetKey={resetKey} view={view} focusKey={focusKey} filter={filter}/>
        <div className="scene-label"><span className="live-dot"/> {project.sample?'EXAMPLE WORKFLOW':'PLAN DEPENDENCIES'} <span>{visibleTasks.length} nodes{filteredTasks.length>visibleTasks.length?` of ${filteredTasks.length} · choose an epic or use task list`:''}</span></div>
        <div className="scene-controls"><button className="icon-btn" title="Reset view (R)" aria-label="Reset view" onClick={()=>setResetKey(k=>k+1)}><ArrowsOut size={18}/></button><div className="control-divider"/><button className="icon-btn" title="Focus selected task" aria-label="Focus selected task" disabled={!task} onClick={()=>setFocusKey(k=>k+1)}><Crosshair size={18}/></button><span className="drag-hint">Drag to orbit <span>·</span> Scroll to zoom</span></div>
        <div className="status-legend">{['all','complete','active','blocked','pending'].map(s=><button key={s} className={`legend-item ${filter===s?'chosen':''} ${s}`} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s!=='all'&&<StatusIcon status={s} size={12}/>}<span>{s==='all'?'All tasks':statusLabel[s]}</span></button>)}</div>
      </div>
      <footer className="statusbar"><div><span className="progress-label">PLAN PROGRESS</span><div className="progress-track"><i style={{width:`${progress}%`}}/></div><strong>{progress}%</strong></div><span><FileText size={13}/>{project.sample?'Sample data':`${plan?.path?.split('/').slice(-2).join('/')} · read only`}</span></footer>
    </main>
    <aside className="inspector" inert={workspaceOpen} id="task-inspector" aria-label="Task inspector" hidden={!task||!inspectorExpanded}>{task&&<><div className="inspector-heading"><span>TASK INSPECTOR</span><button className="icon-btn" aria-label="Collapse task inspector" onClick={collapseInspector}><X size={17}/></button></div><div className="inspector-content"><div className="task-id"><span>{task.id}</span><span className={`status-pill ${task.status}`}><StatusIcon status={task.status} size={12}/>{statusLabel[task.status]}</span></div><h2>{task.title}</h2><div className="task-stage"><span style={{background:lanes.find(l=>l.id===laneFor(task))?.color}}/>{lanes.find(l=>l.id===laneFor(task))?.title}<CaretRight size={11}/>{task.stage||'Unstaged'}</div><div className="inspector-divider"/><dl><div><dt>Owner</dt><dd>{task.owner||'Unassigned'}</dd></div><div><dt>Epic</dt><dd>{task.epicId||'General'}</dd></div><div><dt>Source</dt><dd>{project.sample?'Example plan':`Line ${task.line}`}</dd></div></dl><div className="inspector-section"><h3>ACCEPTANCE CRITERIA</h3><p>{task.acceptance||'No acceptance criterion recorded in this task.'}</p></div><div className="inspector-section"><h3>DEPENDS ON <span>{task.dependencies.length.toString().padStart(2,'0')}</span></h3>{task.dependencies.length?task.dependencies.map(id=>{const dependency=tasks.find(t=>t.id===id);return <button className="dependency-row" key={id} onClick={()=>selectTask(id)} disabled={!dependency}><StatusIcon status={dependency?.status||'pending'} size={16}/><span><small>{id}</small><strong>{dependency?.title||'Outside this plan'}</strong></span><ArrowUpRight size={13}/></button>}):<p className="muted-copy">This task is an entry point.</p>}</div><div className="inspector-section"><h3>UNLOCKS <span>{tasks.filter(t=>t.dependencies.includes(task.id)).length.toString().padStart(2,'0')}</span></h3>{tasks.filter(t=>t.dependencies.includes(task.id)).map(t=><button key={t.id} className="dependency-row" onClick={()=>selectTask(t.id)}><StatusIcon status={t.status} size={15}/><span><small>{t.id}</small><strong>{t.title}</strong></span><ArrowUpRight size={13}/></button>)}</div>{!project.sample&&<div className="inspector-section source-section"><h3>SOURCE PLAN</h3><p>{plan.path}</p></div>}</div><button className="focus-button" onClick={()=>{setFocusKey(k=>k+1);}}><Crosshair size={17}/>Focus in space<ArrowUpRight size={15}/></button></>}</aside>
    <aside className="inspector-toggle-rail" inert={workspaceOpen} aria-label="Task inspector controls" hidden={Boolean(task&&inspectorExpanded)}><button className="icon-btn" aria-label={task ? 'Expand inspector for ' + task.id : 'Select a task to open the inspector'} title={task ? task.id + ' · ' + task.title : 'Select a task to open the inspector'} aria-expanded={Boolean(task&&inspectorExpanded)} aria-controls="task-inspector" disabled={!task} onClick={()=>setInspectorExpanded(true)}><CaretLeft size={17}/></button>{task&&<span className="inspector-rail-selection" title={task.id + ' · ' + task.title}>{task.id}</span>}</aside>
    <input ref={upload} type="file" accept=".md,.markdown,text/markdown,text/plain" multiple hidden onChange={importFiles}/>
    {notice&&<div className="toast" role="status"><Info size={17}/><span>{notice}</span><button className="icon-btn" aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    {(help||taskList||importing)&&<div className="modal-scrim" onClick={()=>{setHelp(false);setTaskList(false);setImporting(false);}}><section className="modal" role="dialog" aria-modal="true" aria-label={importing?'Import a plan':help?'Navigation guide':'Task list'} onClick={e=>e.stopPropagation()}><button className="icon-btn modal-close" autoFocus aria-label="Close dialog" onClick={()=>{setHelp(false);setTaskList(false);setImporting(false);}}><X size={20}/></button>{importing?<><div className="eyebrow">FROM MARKDOWN TO SPACE</div><h2>Bring your plan into view.</h2><p>Choose a plan file, or paste its Markdown below.</p><button className="import-button" onClick={()=>upload.current.click()}><UploadSimple size={17}/>Choose a Markdown file</button><label className="paste-label" htmlFor="plan-markdown">PLAN MARKDOWN</label><textarea id="plan-markdown" placeholder="- [ ] T1.1 Your next move  stage: implement" value={importText} onChange={e=>setImportText(e.target.value)} maxLength={2000000}/><button className="paste-submit" disabled={!importText.trim()} onClick={()=>addImported(importText,'Imported plan.md')}>Explore this plan<ArrowUpRight size={16}/></button><div className="guide-note">Imported plans stay in this browser session. Your source is unchanged.</div></>:help?<><div className="eyebrow">GET YOUR BEARINGS</div><h2>A little space to think.</h2><p>Explore your plan from every angle.</p><div className="guide-row"><Cube size={20}/><span><strong>Orbit & pan</strong><small>Drag the canvas to orbit. Right-drag or two-finger drag to pan.</small></span></div><div className="guide-row"><ArrowsOut size={20}/><span><strong>Move closer</strong><small>Scroll or pinch to zoom. Press R to reset your view.</small></span></div><div className="guide-row"><Crosshair size={20}/><span><strong>Follow the connections</strong><small>Select a task to inspect its criteria, dependencies and the work it unlocks.</small></span></div><div className="guide-note">Source plans stay on your computer. This view is read only.</div></>:<><div className="eyebrow">{project.name}</div><h2>Every step.</h2><p>{filteredTasks.length} tasks in this view</p><div className="all-tasks">{filteredTasks.map(t=><button className="dependency-row" key={t.id} onClick={()=>selectTask(t.id)}><StatusIcon status={t.status} size={17}/><span><small>{t.id} · {statusLabel[t.status]}</small><strong>{t.title}</strong></span><CaretRight size={15}/></button>)}</div></>}</section></div>}
  </div>;
}
